### ISSUE TITLE
Unsupported gpu architecture 'compute_61' on luarocks install cutorch

### ISSUE THREAD

**Issue by michaelzhaoliang** [torch/torch7#764] opened 2016-09-13 08:48 UTC
Dear all

I have a issue when install cutorch. The computer is ubuntu 16, the GPU card is nvidia GTX 1070. I have install CUDA 8.0, cuDNN 5.1. When I install cutorch, I got the following issue:
-- Build files have been written to: /tmp/luarocks_cutorch-scm-1-7995/cutorch/build
[  1%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[  2%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
[  3%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
[  4%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
[  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[  8%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[  9%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at THC_generated_THCHalf.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-7995/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o

**Comment by soumith** [comment] 2016-09-13 14:54
duplicate of https://github.com/torch/cutorch/issues/502

**Closed by soumith** 2016-09-13 14:54 UTC
