### ISSUE TITLE
Unexpected behavior in :set()?

### ISSUE THREAD

**Issue by mbchang** [torch/torch7#655] opened 2016-04-20 23:24 UTC
In the code below I want the first 5 elements in ```c``` to point to the same memory as ```a```, and the last 3 elements in ```c``` to point to the same memory as in ```b```.

I first tried to directly assign the corresponding values of ```c```:
```
th> a = torch.rand(5)
                                                                      [0.0001s]	
th> b = torch.rand(3)
                                                                      [0.0000s]	
th> c = torch.Tensor(8)
                                                                      [0.0000s]	
th> a
 0.1545
 0.7668
 0.0318
 0.7329
 0.8821
[torch.DoubleTensor of size 5]

                                                                      [0.0002s]	
th> b
 0.5529
 0.0916
 0.0858
[torch.DoubleTensor of size 3]

                                                                      [0.0001s]	
th> c
 0
 0
 0
 0
 0
 0
 0
 0
[torch.DoubleTensor of size 8]

                                                                      [0.0002s]	
th> c[{{1,5}}] = a
                                                                      [0.0000s]	
th> c[{{6,8}}] = b
                                                                      [0.0000s]	
th> c
 0.1545
 0.7668
 0.0318
 0.7329
 0.8821
 0.5529
 0.0916
 0.0858
[torch.DoubleTensor of size 8]

                                                                      [0.0001s]	
th> c[1] = 10
                                                                      [0.0000s]	
th> c
 10.0000
  0.7668
  0.0318
  0.7329
  0.8821
  0.5529
  0.0916
  0.0858
[torch.DoubleTensor of size 8]

                                                                      [0.0001s]	
th> a
 0.1545
 0.7668
 0.0318
 0.7329
 0.8821
[torch.DoubleTensor of size 5]

                                                                      [0.0001s]	
th> 
```
But as you can see, I want ```a[1]=10```, which does not happen.

I next tried to use :set() instead:
```
th> a = torch.rand(5)
                                                                      [0.0001s]	
th> b = torch.rand(3)
                                                                      [0.0000s]	
th> c = torch.Tensor(8)
                                                                      [0.0000s]	
th> a
 0.8639
 0.2314
 0.3483
 0.5410
 0.5384
[torch.DoubleTensor of size 5]

                                                                      [0.0002s]	
th> b
 0.2248
 0.5468
 0.7934
[torch.DoubleTensor of size 3]

                                                                      [0.0001s]	
th> c
 0
 0
 0
 0
 0
 0
 0
 0
[torch.DoubleTensor of size 8]

                                                                      [0.0001s]	
th> c[{{1,5}}]:set(a)
 0.8639
 0.2314
 0.3483
 0.5410
 0.5384
[torch.DoubleTensor of size 5]

                                                                      [0.0002s]	
th> c[{{6,8}}]:set(b)
 0.2248
 0.5468
 0.7934
[torch.DoubleTensor of size 3]

                                                                      [0.0001s]	
th> c
 0
 0
 0
 0
 0
 0
 0
 0
[torch.DoubleTensor of size 8]

                                                                      [0.0001s]	
th> c[1] = 10
                                                                      [0.0000s]	
th> c
 10
  0
  0
  0
  0
  0
  0
  0
[torch.DoubleTensor of size 8]

                                                                      [0.0001s]	
th> a
 0.8639
 0.2314
 0.3483
 0.5410
 0.5384
[torch.DoubleTensor of size 5]

                                                                      [0.0001s]	
th> 
```
As you can see, the elements of ```c``` were not modified from what they were originally, let alone set to the values of ```a``` and ```b```. 

What I want to do is to have ```a``` and ```c[{{1,5}}]``` refer to the same memory so that a change in one affects the other, likewise for ```b``` and ```c[{{6,8}}]```. How would you suggest doing this?

**Comment by albanD** [comment] 2016-04-21 08:20
Hi,

The problem in what you are trying to do is that you cannot have a single tensor that refers to two different storage location in memory. Here you try to make `c` look at both `a`'s memory and `b`'s memory.

You can do the same thing by using `c`'s memory and making a and b look inside it. That way each tensor is looking at only a single space in memory. See example below:
```lua
local c = torch.rand(8)

local a = c:narrow(1,1,5)
local b = c:narrow(1,5,3)

print("Original values")
print(a)
print(b)
print(c)

c[1] = 10

print("After changing c[1]")
print(a)
print(b)
print(c)
```

**Comment by mbchang** [comment] 2016-04-21 13:27
That makes sense. The reason I want to do this is that I have two networks, each consisting of an encoder and a decoder. I want them to share the same encoder parameters but have different decoder parameters. I also want to be able to refer to and manipulate the parameter and gradParameter vectors of each network as a whole. 

For example, I have two networks, ```net1``` and ```net2```. The first layer is the encoder and the second layer is the decoder. 

```
require 'nn';

net1 = nn.Sequential()
net1:add(nn.Linear(3,2))
net1:add(nn.Linear(2,1))

net2 = nn.Sequential()
net2:add(nn.Linear(3,2))
net2:add(nn.Linear(2,2))

-- get modules
enc1 = net1.modules[1]
dec1 = net1.modules[2]
enc2 = net2.modules[1]
dec2 = net2.modules[2]

-- weight sharing
enc2:share(enc1,'weight', 'bias')

-- get params (net2 encoder params same as net1 encoder params)
enc1p, enc1gp = enc1:getParameters()  -- net1 encoder
dec1p, dec1gp = dec1:getParameters()  -- net1 decoder
dec2p, dec2gp = dec2:getParameters()  -- net2 decoder

local encp_size = enc1p:size(1)
local dec1p_size = dec1p:size(1)
local dec2p_size = dec2p:size(1)

-- parameter containers
-- net1
net1p = torch.Tensor(encp_size+dec1p_size)
net1p[{{1,encp_size}}] = enc1p
net1p[{{encp_size+1, -1}}] = dec1p

-- net2
net2p = torch.Tensor(encp_size+dec2p_size)
net2p[{{1,encp_size}}] = enc1p
net2p[{{encp_size+1, -1}}] = dec2p
```
Here, ```net1p``` is analogous to ```c```, and ```enc1p``` is analogous to ```a``` in my original post. 

What I want is to do things
- I want the first part of ```net1p``` and the first part of ```net2p``` to refer to the same Storage (this is the encoder parameters, shared across both networks). Then, I want the second part of ```net1p``` and the second part of ```net2p``` to refer to Storages elsewhere (because they aren't shared).
- I want to have variables ```net1p``` and ```net2p``` that refer to the parameter vectors for the entire ```net1``` and the entire ```net2```. This will allow me to do rmsprop updates on each network at different times and modify the respective parameters in place. 

For example, let ```enc1p``` live in Storage 1, ```dec1p``` live in Storage 2, and ```dec2p``` live in Storage 3. Then ```net1p``` refers to values living in Storage 1 and 2, and ```net2p``` refers to values living in Storage 1 and 3. When I update ```net1p```, I want to update values in Storage 1 and 2, and when I update ```net2p```, I want to update values in Storage 1 and 3.

Any suggestions on how to do this?

**Comment by soumith** [comment] 2016-04-28 05:36
you can simply embed net1p and net2p into a dummy Sequential or something, and call getParameters on that. then you'll get net1p+net2p. That's the best i could figure out.

**Comment by soumith** [comment] 2016-04-28 05:37
closing the issue because this is not a bug.

**Closed by soumith** 2016-04-28 05:37 UTC
