### ISSUE TITLE
I can not do install.sh from 8c44a2a8b3340dc531662efcc02ccc32c5413b06 on JetsonTX1

### ISSUE THREAD

**Issue by kiitosu** [torch/torch7#777] opened 2016-09-28 03:42 UTC
I can not do install.sh from 8c44a2a8b3340dc531662efcc02ccc32c5413b06 on JetsonTX1
error code is delow
--------------------
In file included from /home/ubuntu/torch/pkg/torch/lib/TH/THVector.c:2:0:
/home/ubuntu/torch/pkg/torch/lib/TH/generic/THVectorDispatch.c: In function ‘THByteVector_vectorDispatchInit’:
/home/ubuntu/torch/pkg/torch/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in ‘asm’
   asm volatile ( "cpuid\n\t"
   ^
/home/ubuntu/torch/pkg/torch/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in ‘asm’
   asm volatile ( "cpuid\n\t"
   ^
make[2]: *** [lib/TH/CMakeFiles/TH.dir/THVector.c.o] Error 1
make[1]: *** [lib/TH/CMakeFiles/TH.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
---------------------------

How can I handle this?

**Comment by mistertjs** [comment] 2016-10-01 12:56
I'm having the same problem, running Ubuntu 14.04.1 LTS 32 bit. I have gcc/g++ version 4.8.2, but I'm wondering if it's an issue of not being 64bit.

**Comment by dusty-nv** [comment] 2016-10-02 16:13
Please refer to issue [766](https://github.com/torch/torch7/issues/766).

Until the issue is fully resolved in master branch, you can my [script for TX1](https://github.com/dusty-nv/jetson-reinforcement/blob/master/CMakePreBuild.sh) which should be working.

**Comment by soumith** [comment] 2016-10-12 14:30
fixed in https://github.com/torch/torch7/pull/793 thanks to @howard0su

**Closed by soumith** 2016-10-12 14:30 UTC
