### ISSUE TITLE
[Port] Portability problem introduced by THVector.c

### ISSUE THREAD

**Issue by CDLuminate** [torch/torch7#762] opened 2016-09-10 12:15 UTC
Check buildlog here:
https://buildd.debian.org/status/package.php?p=lua-torch-torch7&suite=experimental#problem-1

All architectures fails to build except for x86.

**Comment by soumith** [comment] 2016-09-10 17:54
@rguthrie3 i guess we need an elseif x86 and then finally an else for all other processors....

**Comment by rguthrie3** [comment] 2016-09-10 20:52
Yeah it looks like it.  The fastest fix I think would be to make vectorDispatchInit just return and do nothing (leaving the dispatch pointers initialized to the default implementations) if the SSE macros are not defined.  This should at least allow it to build and work properly everywhere.  The better fix would be to have the x86 macro and change generic/simd/simd.h's conditional compilation accordingly.

**Comment by dusty-nv** [comment] 2016-09-23 12:56
Any update on building for non-x86 architectures?

**Comment by soumith** [comment] 2016-10-12 14:31
fixed in https://github.com/torch/torch7/pull/793 thanks to @howard0su

**Comment by CDLuminate** [comment] 2016-10-13 04:03
Thanks!

**Comment by CDLuminate** [comment] 2016-10-17 01:24
@soumith Please re-open this issue -- as there is still problem on protability of THVector.c

https://buildd.debian.org/status/package.php?p=lua-torch-torch7&suite=experimental

**Comment by howard0su** [comment] 2016-10-17 23:23
Can u try the following patch? https://github.com/torch/torch7/pull/801

I don't know how to run as your log shows. so the testing is only limited to normal build.

from what I can tell from log, seems amd64 is a different issue other than other failed platform. this patch only address the issue on build failure on several platforms.

**Comment by CDLuminate** [comment] 2016-10-18 05:34
@howard0su Thank you, I'll look into it later. But I have to say the amd64 build failure you see was not caused by the same reason as for arm or etc, but invalid simd instruction set -- the build machine doesn't support SSE4.1 (I guess it is quite old a machine but it's indeed amd64).

**Comment by howard0su** [comment] 2016-10-18 08:31
That's my understanding as well. this patch doesn't address that problem. I may look at it later after build break is fixed first.

**Comment by howard0su** [comment] 2016-10-24 14:06
@CDLuminate  any updates on it? after this build problem is confirmed to be fixed, I can look at amd64 problem.

**Comment by CDLuminate** [comment] 2016-10-25 01:30
@howard0su i think i will be available to handle it after Nov 11.

**Comment by CDLuminate** [comment] 2016-10-25 01:35
@howard0su I have solution to the amd64 build failure. The root of trouble lays in packaging.

**Comment by Erhannis** [comment] 2016-11-21 20:46
@CDLuminate Any luck implementing said solution?  Or do you have any other hints about what the problem is?

**Comment by CDLuminate** [comment] 2016-11-22 02:01
I just updated the torch7 package in debian/expeirmental, and you can see the build status there https://buildd.debian.org/status/package.php?p=lua-torch-torch7&suite=experimental

armel fails to build because
```
/«PKGBUILDDIR»/lib/TH/generic/THVectorDispatch.c: In function 'THByteVector_vectorDispatchInit':
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in 'asm'
   asm volatile ( "cpuid\n\t"
   ^~~
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in 'asm'
   asm volatile ( "cpuid\n\t"
   ^~~
```

armhf fails to build because
```
In file included from /«PKGBUILDDIR»/lib/TH/THVector.c:2:0:
/«PKGBUILDDIR»/lib/TH/generic/THVectorDispatch.c: In function 'THByteVector_vectorDispatchInit':
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in 'asm'
   asm volatile ( "cpuid\n\t"
   ^~~
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in 'asm'
   asm volatile ( "cpuid\n\t"
   ^~~
```

mips fails to build because
```
/tmp/ccJIrlkk.s: Assembler messages:
/tmp/ccJIrlkk.s:4250: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:4263: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:4479: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:4492: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:4708: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:4721: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:4937: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:4950: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:5166: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:5179: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:5395: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:5408: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:5626: Error: unrecognized opcode `cpuid'
/tmp/ccJIrlkk.s:5639: Error: unrecognized opcode `cpuid'
```

ppc64el fails to build because
```
In file included from /«PKGBUILDDIR»/lib/TH/THVector.c:2:0:
/«PKGBUILDDIR»/lib/TH/generic/THVectorDispatch.c: In function 'THByteVector_vectorDispatchInit':
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:64:3: error: impossible register constraint in 'asm'
   asm volatile ( "cpuid\n\t"
   ^~~
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:64:3: error: impossible register constraint in 'asm'
   asm volatile ( "cpuid\n\t"
   ^~~
```

**Comment by CDLuminate** [comment] 2016-11-22 02:02
@Erhannis

**Comment by CDLuminate** [comment] 2016-11-22 02:05
FYI, This is an overview of the historical package build status:
https://buildd.debian.org/status/logs.php?pkg=lua-torch-torch7&suite=experimental

**Comment by CDLuminate** [comment] 2017-01-10 02:03
An update on torch7 portability from Debian:

https://buildd.debian.org/status/package.php?p=lua-torch-torch7&suite=experimental#problem-5

Compared to the previous version, armel and armhf build are fixed now, but arm64 failed ...

torch7 version is 0~20170106-gf624ae9-1. I uploaded it yesterday.

**Comment by CDLuminate** [comment] 2017-01-10 02:09
ARM64 failure:
```
In file included from /«PKGBUILDDIR»/lib/TH/THVector.c:3:0:
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h: In function 'detectHostSIMDExtensions':
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:125:21: error: 'SIMDExtension_AVX2' undeclared (first use in this function)
     hostSimdExts |= SIMDExtension_AVX2;
                     ^~~~~~~~~~~~~~~~~~
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:125:21: note: each undeclared identifier is reported only once for each function it appears in
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:130:21: error: 'SIMDExtension_AVX' undeclared (first use in this function)
     hostSimdExts |= SIMDExtension_AVX;
                     ^~~~~~~~~~~~~~~~~
/«PKGBUILDDIR»/lib/TH/generic/simd/simd.h:132:21: error: 'SIMDExtension_SSE' undeclared (first use in this function)
     hostSimdExts |= SIMDExtension_SSE;
                     ^~~~~~~~~~~~~~~~~
```

MIPS, MIPSEL failure:
```
/tmp/ccqqQy7s.s: Assembler messages:
/tmp/ccqqQy7s.s:4250: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:4263: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:4479: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:4492: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:4708: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:4721: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:4937: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:4950: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:5166: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:5179: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:5395: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:5408: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:5626: Error: unrecognized opcode `cpuid'
/tmp/ccqqQy7s.s:5639: Error: unrecognized opcode `cpuid'
```

PPC64EL caught a GCC bug? well...

**Comment by dusty-nv** [comment] 2017-01-10 04:31
Thanks @CDLuminate.  It appears arm64 platforms are not being detected by `__arm__` macro.  Checking for `__arm64` define doesn't help either.  The following patch to `/lib/TH/generic/simd/simd.h` resumes building:

```
56c56
< #if defined(__arm__) || defined(__NEON__)
---
> #if defined(__arm__)
```

**Comment by soumith** [comment] 2017-01-10 05:15
i pushed @dusty-nv's patch via https://github.com/torch/torch7/commit/afed56595cd26ff62f054c0f6381c6eb593c3afa

**Comment by CDLuminate** [comment] 2017-01-10 06:09
@dusty-nv Thank you for the patch. However I disabled NEON on arm* for sake of compatibility, I'm not sure whether the `__NEON__` flag will still be defined.

**Comment by CDLuminate** [comment] 2017-01-10 06:15
According to https://wiki.debian.org/Arm64Port , may we should introduce the arm64 fix with the `__aarch64__` flag?

**Comment by CDLuminate** [comment] 2017-01-10 06:26
@soumith Do you plan to provide support on the MIPS* architecture? If not, I'll omit the mips* results in the future.

**Comment by soumith** [comment] 2017-01-10 06:27
we have no plans to support MIPS

**Comment by CDLuminate** [comment] 2017-01-10 06:27
@soumith Thanks. I'll ignore them in the future.

**Comment by soumith** [comment] 2017-01-10 06:28
The platform we officially support is X86-64, and with community help we are supporting arm32/arm64 and PPC64.

**Comment by CDLuminate** [comment] 2017-01-10 07:39
This patch works on a QEMU-emulated aarch64 machine
```patch
diff --git a/debian/patches/arm64-build-fix.patch b/debian/patches/arm64-build-fix.patch
index d6bb527..959af8c 100644
--- a/debian/patches/arm64-build-fix.patch
+++ b/debian/patches/arm64-build-fix.patch
@@ -13,7 +13,7 @@ index ee53e2c..882b463 100644
  
  
 -#if defined(__arm__)
-+#if defined(__arm__) || defined(__NEON__)
++#if defined(__arm__) || defined(__aarch64__)
  
   #if defined(__NEON__)
```

This is the failure result of the `__NEON__` patch:
http://debomatic-arm64.debian.net/distribution#experimental/lua-torch-torch7/0~20170106-gf624ae9-2/buildlog

This is a success result of my fix:
http://debomatic-arm64.debian.net/distribution#experimental/lua-torch-torch7/0~20170106-gf624ae9-2patch1/buildlog

@soumith

**Comment by CDLuminate** [comment] 2017-01-10 12:25
The arm* build are fixed now:

https://buildd.debian.org/status/package.php?p=lua-torch-torch7&suite=experimental#problem-4

**Comment by CDLuminate** [comment] 2017-01-11 03:33
The ppc64el build failure is due to a GCC bug. See https://github.com/torch/torch7/issues/905

**Comment by soumith** [comment] 2017-01-13 01:22
i'm going to close this now, as we've fixed all platforms from the torch code side

**Closed by soumith** 2017-01-13 01:22 UTC

**Comment by CDLuminate** [comment] 2017-01-13 01:32
OK.
