### ISSUE TITLE
Apple clang is not supported by the nvcc (V8.0.28) when executed by Torch

### ISSUE THREAD

**Issue by shyamalschandra** [torch/torch7#732] opened 2016-08-05 23:26 UTC
What should I do to make it work?  

![screen shot 2016-08-05 at 6 22 47 pm](https://cloud.githubusercontent.com/assets/9545735/17452915/ea82efd0-5b39-11e6-8bd1-60419c1cdd17.png)

**Comment by soumith** [comment] 2016-08-05 23:28
unfortunately, there's not much you can do other than either: 
1. downgrading XCode to 7.3 or so
2. install gcc-4.8 from homebrew and set your CC and CXX environment variables to that, and see if that helps.

Since this is not a bug report in torch, I'm closing the issue.

**Closed by soumith** 2016-08-05 23:28 UTC

**Comment by shyamalschandra** [comment] 2016-08-06 00:37
@soumith Why would I downgrade so low to 7.3 when I am using 8.0 Beta?  Second, why should I need to change the version of the gcc-4.8 so why doesn't torch upgrade so it can handle the latest?  I was the one who pushed Facebook to support Mac OSX for their packages on OSX with an issue comment.  This shouldn't be a problem unless you want me to switch to another deep learning package.  This is definitely a bug in torch, not a bug in my OSX image or XCode build.

**Comment by soumith** [comment] 2016-08-06 00:52
Jeez, calm down :)

Nvidia's cuda does not support clang 8.0. I cannot do anything on my end

**Comment by culurciello** [comment] 2016-08-06 00:56
@shyamalschandra I understand your frustration, I also had to do what Soumith suggested. Unfortunately is the only work around for now, unless you want to spend some more time yourself to investigate. But going to another tool will only make your life harder, as they are not as user friendly as Torch yet. It took many of us a lot of effort, at times, to get some of the packages installed, but that is the price of bleeding (literally!) edge. Stay positive and focus on what is important to you.

**Comment by soumith** [comment] 2016-08-06 01:11
just got to a computer. ok so i cant do anything about it, as the problem is not at the torch end.

> so why doesn't torch upgrade so it can handle the latest? 

NVIDIA's nvcc doesn't support XCode 8.0 yet, clearly. You can switch to another framework, but if you compile any of them from source and they use CUDA, you will run into the same issue.

> I was the one who pushed Facebook to support Mac OSX for their packages on OSX with an issue comment. 

That's nice of you.

> This shouldn't be a problem unless you want me to switch to another deep learning package.

Certainly give every package a try. All packages have their benefits and see what fits you best.

> This is definitely a bug in torch, not a bug in my OSX image or XCode build.
As I pointed out. NO.

**Comment by zhangxiangxiao** [comment] 2016-08-06 06:38
On Linux we could have edited host_config.h header file from cuda for that.

On Apple OSX try this
https://gist.github.com/zchee/7833bf67013e83523181

Just fool nvcc and it usually works. NVIDIA had some very unreasonable constraints put around for nvcc to do compiler version checks. If the actual C++ compiler is newer than what have been tested by NVIDIA, one actually won't be able to compile any CUDA code without a workaround.

I personally think this is complete BS from NVIDIA's end. Forbidding the user from compiling code using a new compiler is utterly wrong. The correct approach is to give linking or run-time error if the code compiled does not work (but why on earth wouldn't it work if the ABI is used correctly, regardless of compiler version?).

I personally have been using CUDA 7.5 and GCC 6.11 (nvcc was incompatible with > 4.9) on Fedora and nothing is wrong so far with these workarounds.

**Comment by elbamos** [comment] 2016-11-21 08:07
This seems to be a perennial issue.... I just hit it again trying to fix my torch installation after upgrading os x.  Does anyone know of instructions for patching nvcc? Either that, or using llvm instead of nvcc to compile cuda code, seems like the right solution.

**Comment by soumith** [comment] 2016-11-21 15:30
@elbamos it's a universal experience :( nvidia's OSX support is not great.

**Comment by elbamos** [comment] 2016-11-21 15:38
Yeah and its not terribly great on linux either.  (I would assign 50% of the blame to Apple, but nvcc is incompatible with LLVM 3.9 also at the moment.)

I just have to imagine that a group with the skill level of this one, faced with an issue that comes up so often, can find a solution.  

I just spent a few minutes poking around the compiling-cuda-with-llvm webpage.  I wonder if that isn't the most sensible direction to head in?  Have you looked at all at what would be entailed in doing that?

**Comment by soumith** [comment] 2016-11-21 15:47
the reason we did not find specific solutions for this problem is:
- 99% of us dont use OSX with CUDA
- we use standard system-shipped compilers to compile all cuda code, and when we use custom compilers, they've been on the gcc side.

**Comment by apaszke** [comment] 2016-11-21 16:29
@elbamos You can register as developer on the Apple website, and when you go to downloads there's a .dmg called "Command Line Tools for XCode 7.3.1" or something similar. Download it and install. This should downgrade your clang.

**Comment by elbamos** [comment] 2016-11-22 04:31
I was able to get it installed using llvm 3.7 from homebrew, modifying install.sh to point to clang in `/usr/local/opt/llvm37/bin`.  If I might suggest, this seems like it would make more sense for the build script than relying on Apple's compiler, and the installation script installs other things with homebrew anyway.  Using llvm will also make openmp available once CUDA supports LLVM 3.8.

**Comment by elbamos** [comment] 2016-11-22 15:41
Not really. It's bottled. Installs in about 2 minutes. We don't need any special components that would require compiling from source.
